apiVersion: v1
kind: Service
metadata:
  name: capoa-controlplane-controller-manager-metrics-service
  namespace: capoa-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: capoa-controlplane-controller-manager
