# permissions for end users to edit openshiftassistedcontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshiftassistedcontrolplanes-editor-role
rules:
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - openshiftassistedcontrolplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - openshiftassistedcontrolplanes/status
  verbs:
  - get
