name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  build:
    env:
      context: "./"
      controlplane_image_name: "cluster-api-controlplane-provider-openshift-assisted"
      bootstrap_image_name: "cluster-api-bootstrap-provider-openshift-assisted"
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get version
        id: get_version
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          echo "Releasing ${VERSION}"
          echo "VERSION=${VERSION//v}" >> $GITHUB_ENV
      - name: Set tags on manifests
        id: set_tag_manifests
        run: |
          sed -i "s,quay.io/edge-infrastructure/cluster-api-bootstrap-provider-openshift-assisted:latest,${{ secrets.REGISTRY_SERVER }}/${{ secrets.REGISTRY_NAMESPACE }}/${{ env.bootstrap_image_name }}:${{env.VERSION}}," bootstrap-components.yaml
          sed -i "s,quay.io/edge-infrastructure/cluster-api-controlplane-provider-openshift-assisted:latest,${{ secrets.REGISTRY_SERVER }}/${{ secrets.REGISTRY_NAMESPACE }}/${{ env.controlplane_image_name }}:${{env.VERSION}}," controlplane-components.yaml
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          name: 'Release ${{ env.VERSION }}'
          files: |
            controlplane-components.yaml
            bootstrap-components.yaml
            metadata.yaml
          generate_release_notes: true
          draft: false
          prerelease: ${{ contains(env.VERSION, 'rc') }}
