name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve build information
        id: build
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          echo "Releasing ${VERSION}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          sed -i "s,quay.io/edge-infrastructure/openshift-capi-agent-bootstrap:latest,quay.io/edge-infrastructure/openshift-capi-agent-bootstrap:${VERSION//v}," bootstrap-components.yaml
          sed -i "s,quay.io/edge-infrastructure/openshift-capi-agent-controlplane:latest,quay.io/edge-infrastructure/openshift-capi-agent-controlplane:${VERSION//v}," controlplane-components.yaml
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          name: 'Release ${{ env.VERSION }}'
          files: |
            controlplane-components.yaml
            bootstrap-components.yaml
            metadata.yaml
          generate_release_notes: true
          draft: false
          prerelease: ${{ contains(env.VERSION, 'rc') }}
